### ISSUE TITLE
Train and evaluation

### ISSUE THREAD

**Issue by liuxing007** [xiu-cs/IGANet#6]
Great work!
(1)  I followed your code for training and testing, and the results are shown in the figure. However, the expected effects mentioned in the paper were not achieved. What could be the reason for this?
(2) Why can uMLP achieve better results? Is this specific to HPE , or is it applicable more generally?

![pic1](https://github.com/xiu-cs/IGANet/assets/129535338/1724d6af-357b-41ef-a86b-3654be9f8210)

**Comment by xiu-cs** [comment]
(1) Indeed, results can vary based on the versions of numpy, pytorch, and even the GPU in use. For optimal reproduction of our results, it would be best to use an NVIDIA 1080ti, as that's the GPU I utilized during model training.

(2) I think uMLP can  be extended to more scenarios, because it is the modified version of MLP in transformer, , you can try its applicability in different tasks.
